local palette = {
  dark0_hard = "#1d2021",
  dark0 = "#282828",
  dark0_soft = "#32302f",
  dark1 = "#3c3836",
  dark2 = "#504945",
  dark3 = "#665c54",
  dark4 = "#7c6f64",
}

local window_background = palette.dark0_hard

return {
    PmenuSel = { bg = "#282828", fg = "NONE" },
    Pmenu = { bg = window_background },
    NormalFloat = { bg = window_background },
    FloatBorder = { bg = window_background },

    CmpItemAbbrDeprecated = { strikethrough = true },
    CmpItemAbbrMatch = { fg = "#83a598", bg = "NONE", bold = true },
    CmpItemAbbrMatchFuzzy = { fg = "#83a598", bg = "NONE", bold = true },

    CmpItemMenu = { fg = window_background, bg = "#928374", bold = true },

    CmpItemKindText = { fg = "#af3a03", italic = true },
    CmpItemKindVariable = { fg = "#af3a03", italic = true },
    CmpItemKindMethod = { fg = "#83a598", italic = true },
    CmpItemKindFunction = { fg = "#83a598", italic = true },
    CmpItemKindConstructor = { fg = "#fabd2f", italic = true },
    CmpItemKindUnit = { fg = "#83a598", italic = true },
    CmpItemKindField = { fg = "#83a598", italic = true },
    CmpItemKindClass = { fg = "#fabd2f", italic = true },
    CmpItemKindInterface = { fg = "#fabd2f", italic = true },
    CmpItemKindModule = { fg = "#83a598", italic = true },
    CmpItemKindProperty = { fg = "#83a598", italic = true },
    CmpItemKindValue = { fg = "#af3a03", italic = true },
    CmpItemKindEnum = { fg = "#fabd2f", italic = true },
    CmpItemKindOperator = { fg = "#fabd2f", italic = true },
    CmpItemKindKeyword = { fg = "#d3869b", italic = true },
    CmpItemKindEvent = { fg = "#d3869b", italic = true },
    CmpItemKindReference = { fg = "#d3869b", italic = true },
    CmpItemKindColor = { fg = "#d3869b", italic = true },
    CmpItemKindSnippet = { fg = "#b8bb26", italic = true },
    CmpItemKindFile = { fg = "#83a598", italic = true },
    CmpItemKindFolder = { fg = "#83a598", italic = true },
    CmpItemKindEnumMember = { fg = "#8ec07c", italic = true },
    CmpItemKindConstant = { fg = "#af3a03", italic = true },
    CmpItemKindStruct = { fg = "#fabd2f", italic = true },
    CmpItemKindTypeParameter = { fg = "#fabd2f", italic = true },

    CmpItemKindTextIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindVariableIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindMethodIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindFunctionIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindConstructorIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindUnitIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindFieldIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindClassIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindInterfaceIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindModuleIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindPropertyIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindValueIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindEnumIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindOperatorIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindKeywordIcon = { fg = window_background, bg = "#d3869b", bold = true },
    CmpItemKindEventIcon = { fg = window_background, bg = "#d3869b", bold = true },
    CmpItemKindReferenceIcon = { fg = window_background, bg = "#d3869b", bold = true },
    CmpItemKindColorIcon = { fg = window_background, bg = "#d3869b", bold = true },
    CmpItemKindSnippetIcon = { fg = window_background, bg = "#b8bb26", bold = true },
    CmpItemKindFileIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindFolderIcon = { fg = window_background, bg = "#83a598", bold = true },
    CmpItemKindEnumMemberIcon = { fg = window_background, bg = "#8ec07c", bold = true },
    CmpItemKindConstantIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindStructIcon = { fg = window_background, bg = "#fabd2f", bold = true },
    CmpItemKindTypeParameterIcon = { fg = window_background, bg = "#fabd2f", bold = true },


}
