return {
    PmenuSel = { bg = "#282828", fg = "NONE" },
    Pmenu = { bg = "#32302f" },

    CmpItemAbbrDeprecated = { strikethrough = true },
    CmpItemAbbrMatch = { fg = "#83a598", bg = "NONE", bold = true },
    CmpItemAbbrMatchFuzzy = { fg = "#83a598", bg = "NONE", bold = true },

    CmpItemMenu = { fg = "#32302f", bg = "#928374", bold = true },

    CmpItemKindText = { fg = "#af3a03", italic = true },
    CmpItemKindVariable = { fg = "#af3a03", italic = true },
    CmpItemKindMethod = { fg = "#83a598", italic = true },
    CmpItemKindFunction = { fg = "#83a598", italic = true },
    CmpItemKindConstructor = { fg = "#fabd2f", italic = true },
    CmpItemKindUnit = { fg = "#83a598", italic = true },
    CmpItemKindField = { fg = "#83a598", italic = true },
    CmpItemKindClass = { fg = "#fabd2f", italic = true },
    CmpItemKindInterface = { fg = "#fabd2f", italic = true },
    CmpItemKindModule = { fg = "#83a598", italic = true },
    CmpItemKindProperty = { fg = "#83a598", italic = true },
    CmpItemKindValue = { fg = "#af3a03", italic = true },
    CmpItemKindEnum = { fg = "#fabd2f", italic = true },
    CmpItemKindOperator = { fg = "#fabd2f", italic = true },
    CmpItemKindKeyword = { fg = "#d3869b", italic = true },
    CmpItemKindEvent = { fg = "#d3869b", italic = true },
    CmpItemKindReference = { fg = "#d3869b", italic = true },
    CmpItemKindColor = { fg = "#d3869b", italic = true },
    CmpItemKindSnippet = { fg = "#b8bb26", italic = true },
    CmpItemKindFile = { fg = "#83a598", italic = true },
    CmpItemKindFolder = { fg = "#83a598", italic = true },
    CmpItemKindEnumMember = { fg = "#8ec07c", italic = true },
    CmpItemKindConstant = { fg = "#af3a03", italic = true },
    CmpItemKindStruct = { fg = "#fabd2f", italic = true },
    CmpItemKindTypeParameter = { fg = "#fabd2f", italic = true },

    CmpItemKindTextIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindVariableIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindMethodIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindFunctionIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindConstructorIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindUnitIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindFieldIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindClassIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindInterfaceIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindModuleIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindPropertyIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindValueIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindEnumIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindOperatorIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindKeywordIcon = { fg = "#32302f", bg = "#d3869b", bold = true },
    CmpItemKindEventIcon = { fg = "#32302f", bg = "#d3869b", bold = true },
    CmpItemKindReferenceIcon = { fg = "#32302f", bg = "#d3869b", bold = true },
    CmpItemKindColorIcon = { fg = "#32302f", bg = "#d3869b", bold = true },
    CmpItemKindSnippetIcon = { fg = "#32302f", bg = "#b8bb26", bold = true },
    CmpItemKindFileIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindFolderIcon = { fg = "#32302f", bg = "#83a598", bold = true },
    CmpItemKindEnumMemberIcon = { fg = "#32302f", bg = "#8ec07c", bold = true },
    CmpItemKindConstantIcon = { fg = nil, bg = "#af3a03", bold = true },
    CmpItemKindStructIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
    CmpItemKindTypeParameterIcon = { fg = "#32302f", bg = "#fabd2f", bold = true },
}
